### ISSUE TITLE
STDERR: no previously-included directories found matching '_build' during vagrant up.

### ISSUE THREAD

**Issue by pramttl** [xuwang/mailman3-vbox#1]
I tried to use vagrant and this repository to setup a mailman VM but towards the end (After a lot of modules are installed), II see this traceback:

```
Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for postorius==1.0.0a1
STDERR: no previously-included directories found matching '_build'
zip_safe flag not set; analyzing archive contents...
python: can't open file 'setup.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
---- End output of "bash"  "/tmp/chef-script20140204-2095-1yl738j-0" ----
Ran "bash"  "/tmp/chef-script20140204-2095-1yl738j-0" returned 1
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by xuwang** [comment]
Sorry for the long long delay!
I have updated all packages and it should build now.
