### ISSUE TITLE
stdin: is not a tty

### ISSUE THREAD

**Issue by Fil** [xuwang/mailman3-vbox#2]
installing with vagrant on a Mac OS X host with the most recent Virtualbox.app:

```
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Uploading chef encrypted data bag secret key...
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-05-08T18:13:33+00:00] INFO: Forking chef instance to converge...
==> default: [2015-05-08T18:13:33+00:00] INFO: *** Chef 12.3.0 ***
==> default: [2015-05-08T18:13:33+00:00] INFO: Chef-client pid: 1605
==> default: [2015-05-08T18:13:34+00:00] INFO: Setting the run_list to ["recipe[chef-solo-search]", "role[base]", "recipe[mailman3]", "recipe[mailman3::test_list]", "recipe[mailman3::web]"] from CLI options
==> default: [2015-05-08T18:13:34+00:00] INFO: Run List is [recipe[chef-solo-search], role[base], recipe[mailman3], recipe[mailman3::test_list], recipe[mailman3::web]]
==> default: [2015-05-08T18:13:34+00:00] INFO: Run List expands to [chef-solo-search, users::sysadmins, sudo, apt, git, build-essential, vim, mailman3, mailman3::test_list, mailman3::web]
==> default: [2015-05-08T18:13:34+00:00] INFO: Starting Chef Run for list.talltree.com
==> default: [2015-05-08T18:13:34+00:00] INFO: Running start handlers
==> default: [2015-05-08T18:13:34+00:00] INFO: Start handlers complete.
==> default: [2015-05-08T18:13:35+00:00] ERROR: Running exception handlers
==> default: [2015-05-08T18:13:35+00:00] ERROR: Exception handlers complete
==> default: [2015-05-08T18:13:35+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-05-08T18:13:35+00:00] ERROR: Cookbook loaded at path(s) [/tmp/vagrant-chef-3/chef-solo-1/cookbooks/vim] has invalid metadata: The `name' attribute is required in cookbook metadata
==> default: [2015-05-08T18:13:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
i
```

and `/var/chef/cache/chef-stacktrace.out` has :

```
Generated at 2015-05-08 18:13:35 +0000
Chef::Exceptions::MetadataNotValid: Cookbook loaded at path(s) [/tmp/vagrant-chef-3/chef-solo-1/cookbooks/vim] has invalid metadata: The `name' attribute is required in cookbook metadata
/opt/chef/embedded/apps/chef/lib/chef/cookbook/cookbook_version_loader.rb:190:in `raise_metadata_error!'
/opt/chef/embedded/apps/chef/lib/chef/cookbook/cookbook_version_loader.rb:79:in `load'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:83:in `block in load_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:82:in `each'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:82:in `load_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:72:in `block in load_cookbooks'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:71:in `each'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:71:in `load_cookbooks'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:71:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:256:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:454:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:51:in `load'
```

**Comment by xuwang** [comment]
Sorry for the delay. fixed the tty error and cookbooks/vim (missing name: section).

**Comment by Fil** [comment]
Thanks! I just had to put back `http://files.vagrantup.com/precise64.box` in the Vagrantfile to get it going on my system (OS X 10.10.4 + VirtualBox).
